{% set version = "2.7.1" %}

package:
  name: tensorflow-split
  version: {{ version }}

source:
  - url: https://github.com/tensorflow/tensorflow/archive/refs/tags/v{{ version }}.tar.gz
    sha256: abebe2cf5ca379e18071693ca5f45b88ade941b16258a21cc1f12d77d5387a21
    patches:
      - patches/0001-relax-tolerence-in-special_math_test.patch
      - patches/0002-skip-read-only-debugger_cli_common-test.patch
      - patches/0003-relax-precision-in-matrix_log_op_test.patch
      # requires setting GRPCIO_VERSION in build script
      - patches/0004-loosen-requirements.patch
      - patches/0005-Replace-deprecated-absl-Status-error_message-call-wi.patch
  - url: https://github.com/tensorflow/estimator/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e5164e802638d3cf110ecc17912be9d514a9d3354ec48e77200b9403dcc15965
    folder: tensorflow-estimator

build:
  number: 0
  skip: true  # [win]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - bazel
    - bazel >=4.2.1  # [osx and arm64]
    - grpc-cpp
    - libprotobuf
    - nasm
    - sed
    - rsync  # [linux]
    # realpath is not available from the docker image for cuda <= 10.2
    # so we install coreutils here
    - coreutils  # [cuda_compiler_version != "None"]
  host:
    # GPU requirements for CUDA
    - cudnn      # [cuda_compiler_version != "None"]
    - nccl       # [cuda_compiler_version != "None"]
    # conda build requirements
    - python
    - pip
    - zlib
    - libpng
    - libcurl
    - curl         # [win]
    - unzip        # [not win]
    - zip          # [not win]
    - m2-unzip     # [win]
    - m2-zip       # [win]
    - openjdk >=8
    - nsync
    # TF_SYSTEM_LIBS, see usage in
    # https://github.com/tensorflow/tensorflow/blob/v{{ version }}/third_party/systemlibs/syslibs_configure.bzl
    # their versions are specified in
    # https://github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/workspace2.bzl
    # but so far there have been no problems with leaving these
    # unpinned; though some restrictions come in for packages
    # that are also listed as a requirement for the pip_package.
    - astor
    - cython
    - dill
    - giflib
    - grpc-cpp
    # 2022/04/25 hmaarrfk
    # the latest flatbuffers 2.0.6 seems to have removed a sybmol in a patch release...
    # https://github.com/Qengineering/TensorFlow_Lite_Pose_RPi_64-bits/issues/3#issuecomment-1034799822
    - flatbuffers 2.0.0
    - icu
    - jpeg
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
    # requirements specified by the package itself, see
    # github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/tools/pip_package/setup.py
    - absl-py >=0.4.0
    - astunparse >=1.6.0
    - gast >=0.2.1,<0.5.0
    - google-pasta >=0.1.1
    - h5py >=2.9.0
    - keras-preprocessing >=1.1.1
    - numpy
    - opt_einsum >=2.3.2
    - protobuf >=3.9.2
    - python-flatbuffers >=1.12,<3
    - six >=1.12
    - termcolor >=1.1.0
    - typing_extensions >=3.6.6
    - wrapt >=1.11.0
    # TF-API needs to move in sync
    # XXX: actually, TF 2.7.0 still demands tb 2.6
    - tensorboard >=2.6,<2.7
    - keras >=2.7,<2.8

outputs:
  # 2021/12/29: hmaarrfk
  # as of tensorflow 2.7.0 we need the tensorflow-base package to break
  # circular dependency when buliding tensorflow extra packages This annoying
  # circularity is broken upstream by the fact that they have to bootstrap
  # their builds
  - name: tensorflow-base
    script: build_pkg.sh  # [not win]
    script: build_pkg.bat  # [win]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      # weigh down cpu implementation and give cuda preference
      track_features:
        - tensorflow-cpu          # [cuda_compiler_version == "None"]
      entry_points:
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        # The tensorboard package adds this entry point.
        # - tensorboard = tensorboard.main:run_main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      host:
        # GPU reuqirements
        - cudnn                   # [cuda_compiler_version != "None"]
        - nccl                    # [cuda_compiler_version != "None"]
        # conda build requirements
        - python
        - pip
        - wheel
        # TF_SYSTEM_LIBS
        - astor
        - cython
        - dill
        - giflib
        - grpc-cpp
        - flatbuffers 2.0.0
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - pybind11
        - snappy
        - sqlite
        - zlib
        # requirements specified by the package itself
        - absl-py >=0.4.0
        - astunparse >=1.6.0
        - gast >=0.2.1,<0.5.0
        - google-pasta >=0.1.1
        - h5py >=2.9.0
        - keras-preprocessing >=1.1.1
        - numpy
        - opt_einsum >=2.3.2
        - protobuf >=3.9.2
        - python-flatbuffers >=1.12,<3
        - six >=1.12
        - termcolor >=1.1.0
        - typing_extensions >=3.6.6
        - wrapt >=1.11.0
        # TF-API needs to move in sync
        # XXX: actually, TF 2.7.0 still demands tb 2.6
        - tensorboard >=2.6,<2.7
        - keras >=2.7,<2.8
      run:
        - python
        - absl-py >=0.4.0
        - astunparse >=1.6.0
        - gast >=0.2.1,<0.5.0
        - google-pasta >=0.1.1
        - grpcio {{ grpc_cpp }}.*
        - h5py >=2.9.0
        - keras-preprocessing >=1.1.1
        - {{ pin_compatible('numpy') }}
        - opt_einsum >=2.3.2
        - protobuf >=3.9.2
        - python-flatbuffers >=1.12,<3
        - six >=1.12
        - termcolor >=1.1.0
        - typing_extensions >=3.6.6
        - wrapt >=1.11.0
        # TF-API needs to move in sync
        # XXX: actually, TF 2.7.0 still demands tb 2.6
        - tensorboard >=2.6,<2.7
        - keras >=2.7,<2.8
        # avoid that people without GPUs needlessly download ~0.5-1GB
        - __cuda  # [cuda_compiler_version != "None"]
    # TODO: decide on the name of the package
    # run_constrained:
    #   What is the difference between these two packages?
    #   - tensorflow-io-gcs-filesystem >=0.21.0
    #   - tensorflow-io >=0.21.0

  - name: tensorflow
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      # weigh down cpu implementation and give cuda preference
      track_features:
        - tensorflow-cpu          # [cuda_compiler_version == "None"]
    requirements:
      host:
        # Require python so that the CONDA_PY gets populated
        - python
      run:
        - python
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
        - {{ pin_subpackage('tensorflow-estimator', exact=True) }}
        # avoid that people without GPUs needlessly download ~0.5-1GB
        # This also helps mamba give preference to the CPU build
        - __cuda  # [cuda_compiler_version != "None"]
    test:
      files:
        - test_tensorflow.py
      requires:
        - pip
      imports:
        - tensorflow
      commands:
        - pip check
        - cat test_tensorflow.py    # [unix]
        - python test_tensorflow.py
        - tf_upgrade_v2 --help
        - saved_model_cli --help
        - tflite_convert --help     # [not win]
        - toco_from_protos --help   # [not win]
        - toco --help               # [not win]

  - name: tensorflow-estimator
    script: build_estimator.sh   # [not win]
    script: build_estimator.bat  # [win]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - bazel
        - bazel >=4.2.1  # [osx and arm64]
      host:
        - python
        - pip
        - setuptools
        - wheel
        # This ensures that a consistent version of openssl is chosen between
        # all packages.
        # https://github.com/conda-forge/conda-forge.github.io/issues/1528
        - openssl
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('tensorflow-base', exact=True) }}
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: libtensorflow
    script: cp_libtensorflow.sh
    build:
      skip: true  # [not linux]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      run_exports:
        # tensorflow makes no ABI guarantees, need to pin to what we built with
        - libtensorflow {{ version }}
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      # host requirements to pick up run_exports
      host:
        - giflib
        - grpc-cpp
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - snappy
        - sqlite
        - zlib
      run:
        # avoid that people without GPUs needlessly download ~200-300MB
        - __cuda  # [cuda_compiler_version != "None"]
    test:
      files:
        - test_libtensorflow.sh
        - test_c.c
      requires:
        - {{ compiler('c') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow.so  # [not win and cuda_compiler_version == "None"]
        - ./test_libtensorflow.sh               # [not win and cuda_compiler_version == "None"]

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh
    build:
      skip: true  # [not linux]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      run_exports:
        # tensorflow makes no ABI guarantees, need to pin to what we built with
        - libtensorflow_cc {{ version }}
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Keep the cuda compiler here since it helps package solvers
        # decide on the cuda variant
        # https://github.com/conda-forge/tensorflow-feedstock/issues/162
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      # host requirements to pick up run_exports
      host:
        - giflib
        - grpc-cpp
        - icu
        - jpeg
        - libcurl
        - libpng
        - libprotobuf
        - openssl
        - snappy
        - sqlite
        - zlib
      run:
        # avoid that people without GPUs needlessly download ~200-300MB
        - __cuda  # [cuda_compiler_version != "None"]
    test:
      files:
        - test_libtensorflow_cc.sh
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win and cuda_compiler_version == "None"]
        - ./test_libtensorflow_cc.sh               # [not win and cuda_compiler_version == "None"]

  # 2021/08/01, hmaarrfk
  # While this seems like a roundabout way of defining the package name
  # It helps the linter avoid errors on a package not having tests.
  {% set tensorflow_cpu_gpu = "tensorflow-cpu" %}   # [cuda_compiler_version == "None" or cuda_compiler_version is undefined]
  {% set tensorflow_cpu_gpu = "tensorflow-gpu" %}   # [cuda_compiler_version != "None"]
  - name: {{ tensorflow_cpu_gpu }}
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
    requirements:
      run:
        - {{ pin_subpackage("tensorflow", exact=True) }}
    test:
      imports:
        - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an end-to-end open source platform for machine learning.
  description: |
    TensorFlow offers multiple levels of abstraction so you can choose the
    right one for your needs. Build and train models by using the high-level
    Keras API, which makes getting started with TensorFlow and machine learning
    easy.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  feedstock-name: tensorflow
  recipe-maintainers:
    - farhantejani
    - ghego
    - h-vetinari
    - hajapy
    - jschueller
    - njzjz
    - waitingkuo
    - xhochy
    - hmaarrfk
    - wolfv
